name: Cross-Platform Build
on:
  push:
    tags:
      - 'v*'
jobs:
  build_on_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: windows-node-${{ hashFiles('pubspeck.lock') }}
          restore-keys: |
            windows-node-
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --prefer-offline --legacy-peer-deps

      - name: Build
        run: npm run package

      - name: List release folder
        run: dir release/build/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/build/*.exe
            release/build/*.msi
            release/build/*.appx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
